### ISSUE TITLE
config options

### ISSUE THREAD

**Issue by Saxmaster** [PbJBOSS/SolarAnnihilation#1]
Would it be possible to add in a section to the configs to make armors protect the player? IE: the top tier magical crops armor. If this isnt possible, could i hardcode it myself?

**Comment by PbJBOSS** [comment]
Yeah should be possible. So you want a config option where you add a list of armor pieces that protect players from damage right, not just a true or false does armor protect the player?

**Comment by PbJBOSS** [comment]
Added.

**Comment by Saxmaster** [comment]
correct. Only the specified armors make the player immune to the damage
